#version: '3.8'

services:
  php:
    build:
      context: .
    volumes:
      - .:/var/www/html
    environment:
      XDEBUG_MODE: "${XDEBUG_MODE:-debug}"  # Enable Xdebug for development (optional)
    extra_hosts:
      - "host.docker.internal:host-gateway"  # For local communication (useful on Linux/Mac)
    tty: true  # Keep container alive for debugging

  database:
    ports:
      - "3306:3306"  # Expose MySQL's port (optional)
